// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project/person.proto

package org.lab.arm.quarkus.grpc.model;

public interface CreatePersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PersonEntity person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.PersonEntity person = 1;</code>
   * @return The person.
   */
  PersonEntity getPerson();
  /**
   * <code>.PersonEntity person = 1;</code>
   */
  PersonEntityOrBuilder getPersonOrBuilder();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
