// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project/person_service.proto

package org.lab.arm.quarkus.grpc.service;

public final class PersonServiceProto {
  private PersonServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034project/person_service.proto\032\024project/" +
      "person.proto2H\n\rPersonService\0227\n\006Create\022" +
      "\024.CreatePersonRequest\032\025.CreatePersonResp" +
      "onse\"\000B8\n org.lab.arm.quarkus.grpc.servi" +
      "ceB\022PersonServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.lab.arm.quarkus.grpc.model.PersonDomainProto.getDescriptor(),
        });
    org.lab.arm.quarkus.grpc.model.PersonDomainProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
