// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project/person.proto

package org.lab.arm.quarkus.grpc.model;

public final class PersonDomainProto {
  private PersonDomainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePersonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024project/person.proto\"7\n\013PhoneNumber\022\016\n" +
      "\006number\030\001 \001(\t\022\030\n\004type\030\002 \001(\0162\n.PhoneType\"" +
      "\216\001\n\014PersonEntity\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001" +
      "(\003\022\r\n\005email\030\003 \001(\t\022\034\n\006phones\030\004 \003(\0132\014.Phon" +
      "eNumber\022\021\n\tcreatedAt\030\005 \001(\003\022\021\n\tupdatedAt\030" +
      "\006 \001(\003\022\021\n\tdeletedAt\030\007 \001(\003\"\\\n\023CreatePerson" +
      "Request\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\022\r\n\005ema" +
      "il\030\003 \001(\t\022\034\n\006phones\030\004 \003(\0132\014.PhoneNumber\"W" +
      "\n\024CreatePersonResponse\022\035\n\006person\030\001 \001(\0132\r" +
      ".PersonEntity\022\017\n\007success\030\002 \001(\010\022\017\n\007messag" +
      "e\030\003 \001(\t*+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME" +
      "\020\001\022\010\n\004WORK\020\002B5\n\036org.lab.arm.quarkus.grpc" +
      ".modelB\021PersonDomainProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhoneNumber_descriptor,
        new String[] { "Number", "Type", });
    internal_static_PersonEntity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PersonEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonEntity_descriptor,
        new String[] { "Name", "Id", "Email", "Phones", "CreatedAt", "UpdatedAt", "DeletedAt", });
    internal_static_CreatePersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreatePersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePersonRequest_descriptor,
        new String[] { "Name", "Id", "Email", "Phones", });
    internal_static_CreatePersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreatePersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePersonResponse_descriptor,
        new String[] { "Person", "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
